### ISSUE TITLE
ask snif

### ISSUE THREAD

**Issue by lintangtimur** [BroNils/LINE-Source#1]
i'm interested about how to sniff LINE protocol, how do people reverse thrift from LINE, like what carpedm doing. the point im asking is, if i want to make pull request for some new feature, i must know about their API's and how these work.
thanks

**Comment by BroNils** [comment]
> Reverse the latest LINE apk
> Understand the code (ez obfuscate)
> And build your LINE Protocol Thrift

**Comment by BroNils** [comment]
or you can simply sniff the packet

**Comment by lintangtimur** [comment]
i decompiled using dex2jar and then open via JD gui, but the code is obfuscated, any tools can deobfuscate this code?
sniff line packet with wireshark is encrypted, im tried in android device with ssl capture, but sometimes it same too (encrypted)

sorry bad english

**Comment by BroNils** [comment]
-Jangan make dex2jar, pake aja JADX.
-Trus code obfuscate itu kalo mau deobfus harus make metode yg sama
-Android capture make Packet Capture atau proxymon

**Comment by BroNils** [comment]
Lagipula obfuscate-nya masih bisa dibaca kok. Kalo agan tau java pasti bisa baca

**Comment by lintangtimur** [comment]
sry salah, saya pake juga packet ccapture, tapi saya liat itu juga ada yang tidak bisa dibaca.
saya masih basic java sih, cuma variable nya keobfuscate aga bingung.

berarti gimana kalo pake metode yg sama?

**Comment by BroNils** [comment]
intinya kalo mau deobfuscate, ente harus tau pihak LINE gunain apa untuk obfuscate... nah nanti gunakan alat / cara yang sama untuk deobfuscate. Mending daripada cari cara deobfuscate, coba ente pahamin code obfuscatednya aja. Ini masih easy-obfuscated-code, blom sampe hard yang bener-bener cuma hash isinya dan butuh pihak-3 untuk deobfuscate.

**Comment by BroNils** [comment]
Dari yang gw tau, packet capture cuma bisa nampilin output/input dalam bentuk string (untuk thrift). jadi kemungkinan output/input yang berbentuk struct/enum tidak terbaca
